baseURL = "/"
paginate = "10"

title = "Observatoire Accessibilit√©"

languageCode = "fr-FR"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
enableGitInfo = true


[outputformats]
  _merge = 'deep'

[outputFormats.declarationpage]
  baseName = "declaration"
  mediaType = "text/html"
  notAlternative = false
  permalinkable = true
  isHTML = true
[outputFormats.declaration]
  baseName = "declaration"
  mediaType = "text/plain"
  isPlainText = true
  notAlternative = false
[outputFormats.accessibilitypage]
  baseName = "accessibility"
  mediaType = "text/html"
  notAlternative = false
  permalinkable = true
  isHTML = true
[outputFormats.accessibilitycsv]
  baseName = "accessibility"
  mediaType = "text/csv"
  isPlainText = true
  notAlternative = false
[outputFormats.accessibility]
  baseName = "accessibility"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.qualitypage]
  baseName = "quality"
  mediaType = "text/html"
  notAlternative = false
  permalinkable = true
  isHTML = true
[outputFormats.qualitycsv]
  baseName = "quality"
  mediaType = "text/csv"
  isPlainText = true
  notAlternative = false
[outputFormats.quality]
  baseName = "quality"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
[outputFormats.performancepage]
  baseName = "performance"
  mediaType = "text/html"
  isPlainText = true
  notAlternative = false
  permalinkable = true
  isHTML = true
[outputFormats.performancecsv]
  baseName = "performance"
  mediaType = "text/csv"
  isPlainText = true
  notAlternative = false
[outputFormats.performance]
  baseName = "performance"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false
